package main

MIN_AIR_HOPS :: 2
MAX_AIR_HOPS :: 6
MIN_SEA_HOPS :: 1
MAX_SEA_HOPS :: 2
MIN_LAND_HOPS :: 1
MAX_LAND_HOPS :: 2
AIR_MOVE_SIZE :: 1 + MAX_AIR_HOPS - MIN_AIR_HOPS
SEA_MOVE_SIZE :: 1 + MAX_SEA_HOPS - MIN_SEA_HOPS
LAND_MOVE_SIZE :: 1 + MAX_LAND_HOPS - MIN_LAND_HOPS
PLAYERS_COUNT_P1 :: PLAYERS_COUNT + 1
AIRS_COUNT :: LANDS_COUNT + SEAS_COUNT
MAX_AIR_TO_AIR_CONNECTIONS :: 7
ACTION_COUNT :: max(AIRS_COUNT, len(SeaUnitTypesEnum) + 1)
